<?php
return [
    'contact-basic' => [
        'label' => 'Standaard contactformulier',
        'intro' => 'Verzamel de belangrijkste contactgegevens voor een snelle opvolging.',
        'method' => 'POST',
        'class' => 'row g-3 sh-form-template',
        'fields' => [
            [
                'type' => 'text',
                'name' => 'full_name',
                'label' => 'Naam',
                'placeholder' => 'Voor- en achternaam',
                'required' => true,
                'col' => 'col-md-6',
            ],
            [
                'type' => 'email',
                'name' => 'email',
                'label' => 'E-mailadres',
                'placeholder' => 'naam@bedrijf.nl',
                'required' => true,
                'col' => 'col-md-6',
            ],
            [
                'type' => 'tel',
                'name' => 'phone',
                'label' => 'Telefoonnummer',
                'placeholder' => '06 12345678',
                'required' => false,
                'col' => 'col-md-6',
            ],
            [
                'type' => 'select',
                'name' => 'preferred_contact',
                'label' => 'Voorkeurskanaal',
                'placeholder' => 'Maak een keuze',
                'options' => [
                    ['value' => 'phone', 'label' => 'Telefoon'],
                    ['value' => 'email', 'label' => 'E-mail'],
                ],
                'col' => 'col-md-6',
            ],
            [
                'type' => 'textarea',
                'name' => 'message',
                'label' => 'Bericht',
                'placeholder' => 'Waar kunnen we u mee helpen?',
                'required' => true,
                'rows' => 5,
            ],
        ],
        'hidden' => [
            'form_template' => 'contact-basic',
        ],
        'submit_text' => 'Verstuur bericht',
        'submit_class' => 'btn btn-primary',
    ],
    'quote-request' => [
        'label' => 'Offerte aanvraag',
        'intro' => 'Vraag gerichte informatie of een offerte aan.',
        'method' => 'POST',
        'class' => 'row g-3 sh-form-template',
        'fields' => [
            [
                'type' => 'text',
                'name' => 'company',
                'label' => 'Bedrijfsnaam',
                'required' => true,
                'col' => 'col-md-6',
            ],
            [
                'type' => 'text',
                'name' => 'contact_person',
                'label' => 'Contactpersoon',
                'required' => true,
                'col' => 'col-md-6',
            ],
            [
                'type' => 'email',
                'name' => 'email',
                'label' => 'E-mailadres',
                'required' => true,
                'col' => 'col-md-6',
            ],
            [
                'type' => 'tel',
                'name' => 'phone',
                'label' => 'Telefoonnummer',
                'required' => true,
                'col' => 'col-md-6',
            ],
            [
                'type' => 'select',
                'name' => 'budget',
                'label' => 'Budgetindicatie',
                'options' => [
                    ['value' => '0-1k', 'label' => 'Tot € 1.000'],
                    ['value' => '1-5k', 'label' => '€ 1.000 - € 5.000'],
                    ['value' => '5-10k', 'label' => '€ 5.000 - € 10.000'],
                    ['value' => '10k+', 'label' => '€ 10.000+'],
                ],
                'col' => 'col-md-6',
            ],
            [
                'type' => 'textarea',
                'name' => 'project_details',
                'label' => 'Projectdetails',
                'placeholder' => 'Omschrijf de werkzaamheden of wensen',
                'rows' => 5,
                'required' => true,
            ],
            [
                'type' => 'checkbox',
                'name' => 'terms',
                'label' => 'Ik ga akkoord met de voorwaarden',
                'required' => true,
                'col' => 'col-12',
            ],
        ],
        'hidden' => [
            'form_template' => 'quote-request',
        ],
        'submit_text' => 'Vraag offerte aan',
        'submit_class' => 'btn btn-success',
    ],
    'call-me-back' => [
        'label' => 'Bel mij terug',
        'intro' => 'Laat een telefoonnummer achter zodat we snel kunnen terugbellen.',
        'method' => 'POST',
        'class' => 'row g-3 sh-form-template align-items-end',
        'fields' => [
            [
                'type' => 'text',
                'name' => 'full_name',
                'label' => 'Naam',
                'required' => true,
                'col' => 'col-md-4',
            ],
            [
                'type' => 'tel',
                'name' => 'phone',
                'label' => 'Telefoonnummer',
                'required' => true,
                'col' => 'col-md-4',
            ],
            [
                'type' => 'select',
                'name' => 'time_slot',
                'label' => 'Voorkeurstijd',
                'options' => [
                    ['value' => 'morning', 'label' => 'Ochtend'],
                    ['value' => 'afternoon', 'label' => 'Middag'],
                    ['value' => 'evening', 'label' => 'Avond'],
                ],
                'col' => 'col-md-4',
            ],
        ],
        'hidden' => [
            'form_template' => 'call-me-back',
        ],
        'submit_text' => 'Bel mij terug',
        'submit_class' => 'btn btn-outline-primary w-100',
    ],
];
